global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Claude Code built-in OTEL metrics
  - job_name: "claude-code-otel"
    static_configs:
      - targets: ["localhost:8080"]  # Default OTEL metrics endpoint
    scrape_interval: 10s
    metrics_path: /metrics

  # Prometheus Push Gateway for hook events
  - job_name: "claude-code-hooks"
    static_configs:
      - targets: ["localhost:9091"]  # Push Gateway
    honor_labels: true
    scrape_interval: 5s

  # Additional exporters can be added here
  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
    scrape_interval: 10s