services:
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: claude-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # Prometheus Push Gateway for hook events
  pushgateway:
    image: prom/pushgateway:latest
    container_name: claude-pushgateway
    ports:
      - "9091:9091"

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: claude-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

  # Claude Code container
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code
    environment:
      # Prometheus configuration for hooks
      - PROMETHEUS_PUSH_GATEWAY=http://pushgateway:9091
      
      # User info for tracking - MUST be provided by user
      - USER_NAME=${USER_NAME}
      - USER_EMAIL=${USER_EMAIL}
    volumes:
      - ./workspace:/home/claude-user/workspace
      - ./.claude-template:/home/claude-user/.claude-template
    depends_on:
      - pushgateway
    stdin_open: true
    tty: true
    
    # Graceful shutdown
    stop_grace_period: 10s

volumes:
  prometheus_data:
  grafana_data:
