global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Prometheus Push Gateway for Claude Code hook events
  - job_name: "claude-code-hooks"
    static_configs:
      - targets: ["pushgateway:9091"]
    honor_labels: true
    scrape_interval: 5s