global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Claude Code OTEL built-in metrics
  - job_name: "claude-code-otel"
    static_configs:
      - targets: ["claude-code:8080"]
    scrape_interval: 10s
    metrics_path: /metrics

  # Prometheus Push Gateway for Claude Code hook events
  - job_name: "claude-code-hooks"
    static_configs:
      - targets: ["pushgateway:9091"]
    honor_labels: true
    scrape_interval: 5s